from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

import joblib
import pandas as pd

from pydantic import BaseModel
from app.core.config import settings
from app.schemas.warga import PredictionResult, WargaPredictionInput

logger = logging.getLogger(__name__)

DEFAULT_FEATURES = [
    "Jumlah_Tanggungan",
    "Pendapatan",
    "Pekerjaan_Kode",
    "Kondisi_Rumah_Kode",
    "Pendidikan_Kode",
]

DEFAULT_ENCODINGS: Dict[str, Dict[str, int]] = {
    "kondisi_rumah": {
        "Tidak Layak": 1,
        "Kurang Layak": 2,
        "Sederhana": 3,
        "Layak": 4,
    },
    "pekerjaan": {
        "Tidak Bekerja": 1,
        "Mengurus Rumah Tangga": 1,
        "Buruh Harian Lepas": 2,
        "Buruh Tani": 2,
        "Petani/Pekebun": 3,
        "Ustadz": 3,
        "Pedagang": 3,
        "Perdagangan": 4,
        "Wiraswasta": 4,
        "Karyawan Honorer": 4,
        "Karyawan Swasta": 5,
        "Perangkat Desa": 5,
        "Perawat": 6,
        "Guru": 6,
        "Pensiunan": 6,
        "PNS": 7,
        "TNI": 7,
    },
    "pendidikan": {
        "Tidak Sekolah": 1,
        "SD": 2,
        "SLTP/Sederajat": 3,
        "SLTA/Sederajat": 4,
        "D1": 5,
        "D2": 6,
        "D3": 7,
        "D4": 8,
        "S1": 9,
        "S2": 10,
        "S3": 11,
    },
}


STATUS_LABELS = {
    1: "Layak",
    0: "Tidak Layak",
    "1": "Layak",
    "0": "Tidak Layak",
    "layak": "Layak",
    "tidak layak": "Tidak Layak",
    "tidak_layak": "Tidak Layak",
}


@dataclass
class PredictionArtifact:
    model: Any
    scaler: Any
    metadata: Dict[str, Any]
    feature_order: List[str]


class PredictionEngine:
    def __init__(self, model_path: Optional[str] = None, metadata_path: Optional[str] = None) -> None:
        self.model_path = Path(model_path or settings.MODEL_PATH)
        self.metadata_path = Path(metadata_path or settings.MODEL_METADATA_PATH)
        self.scaler_path = self.model_path.with_name("minmax_scaler.joblib")
        self._artifact: Optional[PredictionArtifact] = None

    @property
    def ready(self) -> bool:
        try:
            self._ensure_loaded()
            return True
        except Exception:
            logger.exception("Prediction engine failed to initialize")
            return False

    def _ensure_loaded(self) -> PredictionArtifact:
        if self._artifact is not None:
            return self._artifact

        metadata = self._load_metadata()
        model = self._load_model()
        scaler = self._load_scaler()
        feature_order = list(metadata.get("features") or DEFAULT_FEATURES)
        self._artifact = PredictionArtifact(
            model=model,
            scaler=scaler,
            metadata=metadata,
            feature_order=feature_order,
        )
        return self._artifact

    def _load_metadata(self) -> Dict[str, Any]:
        if self.metadata_path.exists():
            try:
                with self.metadata_path.open("r", encoding="utf-8") as handle:
                    metadata = json.load(handle)
                    if isinstance(metadata, dict):
                        return metadata
            except Exception as exc:
                logger.warning("Failed to load metadata from %s: %s", self.metadata_path, exc)
        return {
            "version": "0.0.0",
            "best_k": 3,
            "features": DEFAULT_FEATURES,
            "encoding": DEFAULT_ENCODINGS,
            "accuracy_test": 0.0,
            "f1_macro_test": 0.0,
            "artifact_path": str(self.model_path),
            "notes": "Fallback metadata generated by backend scaffold.",
        }

    def _load_model(self) -> Any:
        if self.model_path.exists():
            try:
                return joblib.load(self.model_path)
            except Exception as exc:
                logger.warning("Failed to load model from %s: %s", self.model_path, exc)
        from sklearn.dummy import DummyClassifier

        model = DummyClassifier(strategy="most_frequent")
        model.fit([[0.0] * len(DEFAULT_FEATURES), [1.0] * len(DEFAULT_FEATURES)], [0, 1])
        return model

    def _load_scaler(self) -> Any:
        if self.scaler_path.exists():
            try:
                return joblib.load(self.scaler_path)
            except Exception as exc:
                logger.warning("Failed to load scaler from %s: %s", self.scaler_path, exc)
        return None

    def get_metadata(self) -> Dict[str, Any]:
        artifact = self._ensure_loaded()
        metadata = dict(artifact.metadata)
        metadata.setdefault("features", artifact.feature_order)
        metadata.setdefault("encoding", DEFAULT_ENCODINGS)
        metadata["options"] = self.get_input_options()
        return metadata

    def get_input_options(self) -> Dict[str, List[str]]:
        artifact = self._ensure_loaded()
        encoding = artifact.metadata.get("encoding") or DEFAULT_ENCODINGS
        options: Dict[str, List[str]] = {}
        for field, mapping in encoding.items():
            if isinstance(mapping, dict):
                options[field] = list(mapping.keys())
        if not options:
            options = {field: list(mapping.keys()) for field, mapping in DEFAULT_ENCODINGS.items()}
        return options

    def _normalize_text(self, value: Optional[str]) -> str:
        if value is None:
            return ""
        return " ".join(str(value).strip().lower().replace("-", " ").replace("_", " ").split())

    def normalize_pekerjaan(self, value: str) -> str:
        text = value.strip()
        mapping = {
            "BURUH HARIAN LEPAS": "Buruh Harian Lepas",
            "Buruh Harian Lepas": "Buruh Harian Lepas",
            "Buruh Harian": "Buruh Harian Lepas",
            "PETANI/PEKEBUN": "Petani/Pekebun",
            "Petani": "Petani/Pekebun",
            "Buruh Tani/Perkebunan": "Buruh Tani",
            "GURU": "Guru",
            "Guru Honorer": "Karyawan Honorer",
            "Ibu Rumah Tangga": "Mengurus Rumah Tangga",
            "Belum/Tidak Bekerja": "Tidak Bekerja",
            "Pelajar/Mahasiswa": "Tidak Bekerja",
            "Tentara Nasional Indonesia": "TNI",
            "Ustadz/Mubaligh": "Ustadz",
            "Pensiunan": "Pensiunan",
            "Pensiunan PNS": "Pensiunan",
            "PNS": "PNS",
            "Pegawai Negeri Sipil": "PNS",
            "Pedagang Kecil": "Pedagang",
            "Karyawan": "Karyawan Swasta",
            "Ojek": "Wiraswasta",
            "Penjahit": "Wiraswasta",
            "wiraswasta": "Wiraswasta",
        }
        return mapping.get(text, text)

    def normalize_pendidikan(self, value: str) -> str:
        text = value.strip()
        mapping = {
            "Tamat SLTP/Sederajat": "SLTP/Sederajat",
            "Tamat SLTA/Sederajat": "SLTA/Sederajat",
            "STRATA 1 / D IV": "D4",
        }
        return mapping.get(text, text)

    def _encode_from_map(self, field: str, value: Optional[str]) -> float:
        val_str = str(value or "").strip()
        if field == "pekerjaan":
            val_str = self.normalize_pekerjaan(val_str)
        elif field == "pendidikan":
            val_str = self.normalize_pendidikan(val_str)

        normalized = self._normalize_text(val_str)
        if not normalized:
            return 0.0
        artifact = self._ensure_loaded()
        encoding = artifact.metadata.get("encoding") or {}
        field_map = encoding.get(field) if isinstance(encoding, dict) else None
        if isinstance(field_map, dict):
            for key, encoded_value in field_map.items():
                if self._normalize_text(key) == normalized:
                    return float(encoded_value)
        fallback_map = DEFAULT_ENCODINGS.get(field, {})
        for key, encoded_value in fallback_map.items():
            if self._normalize_text(key) == normalized:
                return float(encoded_value)
        return 0.0

    def _parse_income_value(self, income_text: Optional[str], income_value: Any) -> float:
        if income_value is not None:
            try:
                return float(income_value)
            except (TypeError, ValueError):
                pass
        if not income_text:
            return 0.0

        val_str = str(income_text).strip().replace(" ", "")

        # Map standard ranges and text formats
        income_map = {
            "<500.000": 400000.0,
            "500.000": 500000.0,
            "500.000-1.000.000": 750000.0,
            "1.000.000-2.000.000": 1500000.0,
            "2.000.000-4.000.000": 3000000.0,
            ">4.000.000": 4500000.0,
            # Without dots
            "<500000": 400000.0,
            "500000": 500000.0,
            "500000-1000000": 750000.0,
            "1000000-2000000": 1500000.0,
            "2000000-4000000": 3000000.0,
            ">4000000": 4500000.0,
            # Text variations
            "dibawah1juta": 500000.0,
            "<1jt": 500000.0,
            "1-3juta": 2000000.0,
            "1sampai3juta": 2000000.0,
            "3-5juta": 4000000.0,
            ">5juta": 6000000.0,
            "diatas5juta": 6000000.0,
        }

        # Check raw string
        if val_str in income_map:
            return income_map[val_str]

        # Clean string
        cleaned = val_str.lower().replace("rp", "").replace(".", "").replace(",", ".")
        if cleaned in income_map:
            return income_map[cleaned]

        # If it's a range like "1000000-2000000"
        if "-" in cleaned:
            parts = cleaned.split("-")
            if len(parts) == 2:
                try:
                    p1 = "".join(ch for ch in parts[0] if ch.isdigit() or ch == ".")
                    p2 = "".join(ch for ch in parts[1] if ch.isdigit() or ch == ".")
                    if p1 and p2:
                        return (float(p1) + float(p2)) / 2.0
                except ValueError:
                    pass

        digits = "".join(ch for ch in cleaned if ch.isdigit() or ch == ".")
        if digits:
            try:
                return float(digits)
            except ValueError:
                pass

        # Text mapping check using normalized value
        text_map = {
            "dibawah 1 juta": 500000.0,
            "<1 jt": 500000.0,
            "1-3 juta": 2000000.0,
            "1 sampai 3 juta": 2000000.0,
            "3-5 juta": 4000000.0,
            ">5 juta": 6000000.0,
            "di atas 5 juta": 6000000.0,
        }
        normalized = self._normalize_text(income_text)
        return float(text_map.get(normalized, 0.0))

    def _coerce_payload(self, payload: Any) -> WargaPredictionInput:
        if isinstance(payload, WargaPredictionInput):
            return payload
        if isinstance(payload, BaseModel):
            return WargaPredictionInput(**payload.model_dump())
        if isinstance(payload, dict):
            return WargaPredictionInput(**payload)
        raise TypeError("payload must be a WargaPredictionInput, BaseModel, or dict")

    def _build_features(self, payload: WargaPredictionInput | Dict[str, Any]) -> List[float]:
        payload = self._coerce_payload(payload)
        income_value = self._parse_income_value(payload.pendapatan, payload.pendapatan_nilai)
        feature_values = {
            "jumlah_tanggungan": float(payload.tanggungan),
            "tanggungan": float(payload.tanggungan),
            "pendapatan": income_value,
            "pendapatan_nilai": income_value,
            "pekerjaan_kode": self._encode_from_map("pekerjaan", payload.pekerjaan),
            "pekerjaan": self._encode_from_map("pekerjaan", payload.pekerjaan),
            "kondisi_rumah_kode": self._encode_from_map("kondisi_rumah", payload.kondisi_rumah),
            "kondisi_rumah": self._encode_from_map("kondisi_rumah", payload.kondisi_rumah),
            "pendidikan_kode": self._encode_from_map("pendidikan", payload.pendidikan),
            "pendidikan": self._encode_from_map("pendidikan", payload.pendidikan),
            "jk": self._encode_from_map("jk", payload.jk),
            "hub_kel": self._encode_from_map("hub_kel", payload.hub_kel),
        }
        artifact = self._ensure_loaded()
        features = []
        for feature in artifact.feature_order:
            key = feature.lower()
            val = feature_values.get(key, 0.0)
            features.append(float(val))
        return features

    def _scale_features(self, features: Sequence[float]) -> List[float]:
        artifact = self._ensure_loaded()
        if artifact.scaler is None:
            return list(features)
        try:
            frame = pd.DataFrame([list(features)], columns=artifact.feature_order)
            scaled = artifact.scaler.transform(frame)[0]
            return [float(value) for value in scaled]
        except Exception as exc:
            logger.warning("Failed to scale features with MinMax scaler: %s", exc)
            return list(features)

    def _as_feature_frame(self, features: Sequence[float]) -> pd.DataFrame:
        artifact = self._ensure_loaded()
        return pd.DataFrame([list(features)], columns=artifact.feature_order)

    def _extract_probability(self, model: Any, features: Sequence[float]) -> Dict[str, float]:
        try:
            raw = model.predict_proba(self._as_feature_frame(features))[0]
            classes = list(getattr(model, "classes_", [0, 1]))
            probability_map: Dict[str, float] = {}
            for index, class_label in enumerate(classes):
                normalized_label = self._normalize_status_label(class_label)
                probability_map[normalized_label] = float(raw[index])
            probability_map.setdefault("Layak", 0.0)
            probability_map.setdefault("Tidak Layak", 0.0)
            return probability_map
        except Exception:
            logger.debug("Model does not expose predict_proba; using fallback probability")
            return {"Layak": 0.5, "Tidak Layak": 0.5}

    def _normalize_status_label(self, value: Any) -> str:
        if value in STATUS_LABELS:
            return STATUS_LABELS[value]
        normalized = self._normalize_text(str(value))
        if normalized in STATUS_LABELS:
            return STATUS_LABELS[normalized]
        if normalized in {"layak", "eligible", "eligible for assistance"}:
            return "Layak"
        return "Tidak Layak"

    def predict(self, payload: WargaPredictionInput | Dict[str, Any]) -> PredictionResult:
        artifact = self._ensure_loaded()
        raw_features = self._build_features(payload)
        features = self._scale_features(raw_features)
        prediction = artifact.model.predict(self._as_feature_frame(features))[0]
        status = self._normalize_status_label(prediction)
        probability = self._extract_probability(artifact.model, features)
        layak_probability = float(probability.get("Layak", 0.0))
        tidak_layak_probability = float(probability.get("Tidak Layak", 0.0))
        if status == "Layak" and layak_probability < tidak_layak_probability:
            layak_probability = max(layak_probability, 1.0 - tidak_layak_probability)
        if status == "Tidak Layak" and tidak_layak_probability < layak_probability:
            tidak_layak_probability = max(tidak_layak_probability, 1.0 - layak_probability)

        prediction_code = 1 if status == "Layak" else 0
        keterangan = (
            "Layak menerima bantuan sosial"
            if status == "Layak"
            else "Belum layak menerima bantuan sosial"
        )
        return PredictionResult(
            status=status,
            prediction_code=prediction_code,
            probability={"Layak": layak_probability, "Tidak Layak": tidak_layak_probability},
            keterangan=keterangan,
            features_used=features,
        )


@lru_cache(maxsize=1)
def get_prediction_engine() -> PredictionEngine:
    return PredictionEngine()
